name: Dan Workflow

on:
  push:
     branches: [ "main" ]
  workflow_dispatch:
  issues:
    types: [opened, reopened]
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: echo Hello, World!
    
    
